apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-k9-ettersending-mottatt-v2
  namespace: dusseldorf
  labels:
    team: dusseldorf
spec:
  pool: {{kafka-pool}}
  config: # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 730
  acl:
    - team: dusseldorf
      application: k9-ettersending-api
      access: write
    - team: dusseldorf
      application: k9-ettersending-prosessering
      access: read

---

apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-k9-ettersending-preprosessert
  namespace: dusseldorf
  labels:
    team: dusseldorf
spec:
  pool: {{kafka-pool}}
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 730
  acl:
    - team: dusseldorf
      application: k9-ettersending-prosessering
      access: readwrite

---

apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-k9-ettersending-cleanup
  namespace: dusseldorf
  labels:
    team: dusseldorf
spec:
  pool: {{kafka-pool}}
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 730
  acl:
    - team: dusseldorf
      application: k9-ettersending-prosessering
      access: readwrite
    - team: dusseldorf
      application: sif-innsyn-api
      access: read
